---
- hosts: web
  become: true

  tasks:
  - name: Installing python dependancie for ansible docker stack module
    pip:
      name:
        - jsondiff
        - pyyaml
      state: present

  - name: Clone/Pull latest version of repository
    git:
      repo: https://github.com/EMC-Underground/service_concourse.git
      dest: /tmp/service_concourse
      version: dev
      force: yes

  - name: Generating worker and web certs for session sigining key
    shell: docker run --rm -v $PWD/web:/keys concourse/concourse \
           generate-key -t rsa -f /keys/session_signing_key
    args:
      chdir: /tmp/service_concourse/keys

  - name: Generating worker and web certs for tsa host key
    shell: docker run --rm -v $PWD/web:/keys concourse/concourse \
           generate-key -t ssh -f /keys/tsa_host_key
    args:
      chdir: /tmp/service_concourse/keys

  - name: Generating worker and web certs for worker key
    shell: docker run --rm -v $PWD/worker:/keys concourse/concourse \
           generate-key -t ssh -f /keys/worker_key
    args:
      chdir: /tmp/service_concourse/keys

  - name:
    copy:
      src: /tmp/service_concourse/keys/worker/worker_key.pub
      dest: /tmp/service_concourse/keys/web/authorized_worker_keys
      remote_src: true

  - name:
    copy:
      src: /tmp/service_concourse/keys/web/tsa_host_key.pub
      dest: /tmp/service_concourse/keys/worker
      remote_src: true

  - name: Creating list of web files to copy
    shell: (cd /tmp/service_concourse/keys/web; find . -maxdepth 1 -type f) | cut -d'/' -f2
    register: web_files_to_copy

  - name: Copy web files from vm back to worker container
    fetch:
      src: /tmp/service_concourse/keys/web/{{ item }}
      dest: /tmp/web/
      flat: yes
    with_items:
      - "{{ web_files_to_copy.stdout_lines }}"

  - name: Creating list of worker files to copy
    shell: (cd /tmp/service_concourse/keys/worker; find . -maxdepth 1 -type f) | cut -d'/' -f2
    register: worker_files_to_copy

  - name: Copy web files from vm back to worker container
    fetch:
      src: /tmp/service_concourse/keys/worker/{{ item }}
      dest: /tmp/worker/
      flat: yes
    with_items:
      - "{{ worker_files_to_copy.stdout_lines }}"

  - name: Deploy concourse docker stack
    docker_stack:
      state: absent
      name: cicd
      absent_retries: 5
      absent_retries_interval: 2

  - name: Deploy concourse docker stack
    docker_stack:
      state: present
      name: cicd
      compose:
        - /tmp/service_concourse/docker-compose.yml
    environment:
      VAULT_CLIENT_TOKEN: "{{ vault_key }}"
      POSTGRES_CONCOURSE_PASSWORD: "{{ postgres_pw }}"
      DNS_SUFFIX: "{{ dns_suffix }}"
