---
- hosts: worker
  become: true
  vars:
    concourse_version: 5.8.0
    fly_version: 5.8.0

  tasks:
  - name: Temporarily disable SELinux
    selinux:
      state: permissive
  
  
  - name: Create /opt/concourse
    file:
      path: /opt/concourse
      state: directory
    tags:
      - concourse

  - name: Create /etc/concourse
    file:
      path: /etc/concourse
      state: directory
    tags:
      - concourse

  - name: Copy worker certs
    copy:
      src: /tmp/worker/
      dest: /opt/concourse/keys/
      owner: root
      group: root
      mode: '0440'
    tags:
      - concourse

  - name: Copy concourse systemd file
    copy:
      src: ./concourse_worker.service
      dest: /etc/systemd/system/concourse_worker.service
      owner: root
      group: root
      mode: '0755'
    tags:
      - concourse

  - name: Copy concourse environment file
    copy:
      src: ./concourse_worker.conf
      dest: /etc/concourse/concourse_worker.conf
      owner: root
      group: root
      mode: '0644'
    tags:
      - concourse

  - name: Copy the concourse binary to worker nodes
    copy:
      src: /tmp/concourse
      dest: /usr/local
      mode: '0755'
    tags:
      - concourse


  - name: Create and start our new service
    systemd:
      state: restarted
      daemon_reload: yes
      name: concourse_worker
    tags:
      - concourse
