#!/usr/bin/env ash

set -e -u

cd $(dirname $0)

docker run --rm -v $PWD/web:/keys concourse/concourse \
  generate-key -t rsa -f /keys/session_signing_key

docker run --rm -v $PWD/web:/keys concourse/concourse \
  generate-key -t ssh -f /keys/tsa_host_key

docker run --rm -v $PWD/worker:/keys concourse/concourse \
  generate-key -t ssh -f /keys/worker_key

printf "Current directory: "
echo `pwd`
echo "Directory contents:"
ls -la
echo "Web Directory contents:"
ls -la
echo "Worker Directory contents:"
ls -la

cp ./worker/worker_key.pub ./web/authorized_worker_keys
cp ./web/tsa_host_key.pub ./worker
